# Generated by Django 4.0.2 on 2022-02-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-name']},
        ),
    ]
